Traceback (most recent call last):
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mshira/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# (a, b)の最小値を求めて返す関数
def min1(a, b):
    """return文１つ"""
    if a<b:
        min=a
    else:
        min=b
    return min
    
def min2(a, b):
    """return文2つ"""
    if a<b:
        return a
    return b

n1=int(input('整数n1:'))
n2=int(input('整数n2:'))

print(f'最小値は{min(n1,n2)}です。')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[7], line 16[0m
[1;32m     13[0m         [38;5;28;01mreturn[39;00m a
[1;32m     14[0m     [38;5;28;01mreturn[39;00m b
[0;32m---> 16[0m n1[38;5;241m=[39m[38;5;28mint[39m([38;5;28;43minput[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m整数n1:[39;49m[38;5;124;43m'[39;49m[43m)[49m)
[1;32m     17[0m n2[38;5;241m=[39m[38;5;28mint[39m([38;5;28minput[39m([38;5;124m'[39m[38;5;124m整数n2:[39m[38;5;124m'[39m))
[1;32m     19[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124m最小値は[39m[38;5;132;01m{[39;00m[38;5;28mmin[39m(n1,n2)[38;5;132;01m}[39;00m[38;5;124mです。[39m[38;5;124m'[39m)

File [0;32m~/Dropbox/2024数理工学実験２/2024Shiraishi/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:1281[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1279[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1280[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1281[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1282[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1283[0m     [38;5;28mstr[39m(prompt),
[1;32m   1284[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1285[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1286[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1287[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

